[project]
name = "ems-opensource"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "streamlit>=1.28.0",
    "pandas>=2.0.0",
    "plotly>=5.15.0",
    "pyarrow>=12.0.0",
    "numpy>=1.24.0",
    "altair>=5.0.0",
]
